# Generated by Django 4.1.7 on 2023-04-13 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Resume",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                ("skills", models.TextField()),
                ("location", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("companies_worked", models.TextField()),
                ("graduation_year", models.IntegerField()),
                ("designation", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=20)),
                ("college", models.CharField(max_length=255)),
                ("years_of_experience", models.FloatField()),
                ("resume_file", models.FileField(upload_to="resumes/")),
            ],
        ),
    ]
